### ISSUE TITLE
Dumpsms command app crash

### ISSUE THREAD

**Issue by scriptkiddie262** [Th30neAnd0nly/Ohm#41]
When trying to dumpsms app crash

Log : 

com.google.android.gms.tasks.RuntimeExecutionException: com.google.firebase.storage.StorageException: User does not have permission to access this object.
	at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@17.2.1:3)
	at nikola.tesla.MainActivity$7.onComplete(MainActivity.java:406)
	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8232)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: com.google.firebase.storage.StorageException: User does not have permission to access this object.
	at com.google.firebase.storage.network.NetworkRequest.completeTask(com.google.firebase:firebase-storage@@19.0.0:555)
	at com.google.firebase.storage.GetDownloadUrlTask.run(com.google.firebase:firebase-storage@@19.0.0:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: {  "error": {    "code": 403,    "message": "Permission denied."  }}
	at com.google.firebase.storage.network.NetworkRequest.parseResponse(com.google.firebase:firebase-storage@@19.0.0:438)
	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(com.google.firebase:firebase-storage@@19.0.0:455)
	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(com.google.firebase:firebase-storage@@19.0.0:446)
	at com.google.firebase.storage.network.NetworkRequest.performRequest(com.google.firebase:firebase-storage@@19.0.0:279)
	at com.google.firebase.storage.network.NetworkRequest.performRequest(com.google.firebase:firebase-storage@@19.0.0:293)
	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(com.google.firebase:firebase-storage@@19.0.0:70)
	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(com.google.firebase:firebase-storage@@19.0.0:62)
	at com.google.firebase.storage.GetDownloadUrlTask.run(com.google.firebase:firebase-storage@@19.0.0:74)
	... 3 more

**Comment by prateek-chaubey** [comment]
Seems like you haven't modified the rules of firebase storage

**Comment by scriptkiddie262** [comment]
I have watched videos tutorial, nothing change on storage rule, cmiiw..

This my firebase storage rule :

rules_version = '2';

// Craft rules based on data in your Firestore database
// allow write: if firestore.get(
//    /databases/(default)/documents/users/$(request.auth.uid)).data.isAdmin;
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if false;
    }
  }
}

**Comment by scriptkiddie262** [comment]
Im sorry, i wrong..
I haven't change the value , thanks..
I have solved this..
